# Markdownlint 配置
# 參考：https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# 預設啟用所有規則
default: true

# 行長度限制 - 放寬以適應中文內容
MD013:
  line_length: 300
  heading_line_length: 100
  code_block_line_length: 200

# 標題風格 - 使用 atx 風格 (# heading)
MD003:
  style: atx

# 無序列表標記 - 統一使用 -
MD004:
  style: dash

# 列表縮排 - 2 空格
MD007:
  indent: 2

# 允許多個空行（VitePress frontmatter 需要）
MD012:
  maximum: 2

# 禁用第一行必須是標題的規則（因為有 frontmatter）
MD041: false

# 允許行內 HTML（表格等需要）
MD033:
  allowed_elements:
    - br
    - sup
    - sub
    - kbd
    - mark

# 程式碼區塊樣式
MD046:
  style: fenced

# 程式碼區塊需要指定語言
MD040: true

# 強調符號一致性
MD049:
  style: asterisk

MD050:
  style: asterisk

# 連結樣式
MD034: true  # 裸 URL 警告

# 禁用重複標題規則（允許多個相同標題）
MD024:
  siblings_only: true

# 禁用標題遞增規則（允許跳級）
MD001: false
